Shopify/semian

lib/semian/platform.rb
@Sirupsen, @eapache 
Fixes #15.
=> Change platform check to /linux/

Rakefile, lib/semian.rb, lib/semian/circuit_breaker.rb, lib/semian/platform.rb, lib/semian/protected_resource.rb, lib/semian/resource.rb, lib/semian/version.rb, semian.gemspec, test/test_circuit_breaker.rb
@csfrancis @Sirupsen @fw42 for review please.
(It is missing documentation, but I prefer to do it once we settle on the API etc.)
=> Wrap semian resources with a circuit breaker

lib/semian/mysql2.rb
So. https://github.com/Shopify/semian/pull/21 added a convenient API to monitor Semian itself.
But in many case you also want to instrument how long the original operation take, e.g. Mysql query time, Redis query time, etc.
So for monitoring puprose you need an easy access to the original method so you can do the usual patching mess.
That PR does exactly that, by renaming the original methods that are protected, so that they kind be patched for monitoring purpose.
Long story short: That will allow us to use `StatsD::Instrument` again.
@Sirupsen @fw42 for review please.
=> Alias original Mysql2 methods for easier monitoring

README.md, lib/semian.rb, lib/semian/resource.rb, test/test_circuit_breaker.rb, test/test_instrumentation.rb, test/test_resource.rb, test/test_unsupported.rb
So as we talked before, this remove most of the default values because they can hardly make sense in the abstract.
@Sirupsen for review please.
=> No more default values

.travis.yml, Gemfile, lib/semian.rb, lib/semian/adapter.rb, lib/semian/mysql2.rb, lib/semian/redis.rb, semian.gemspec, test/helpers/background_helper.rb, test/helpers/toxiproxy.json, test/mysql2_test.rb, test/redis_test.rb, test/test_helper.rb
Semian integration for redis-rb
@Sirupsen @fw42 for review please (can totally wait tomorrow)
=> Redis adapter

lib/semian.rb, lib/semian/adapter.rb, lib/semian/mysql2.rb, lib/semian/redis.rb, lib/semian/unprotected_resource.rb, test/mysql2_test.rb, test/redis_test.rb, test/unprotected_resource_test.rb
I initially wrote that because I though we needed it, but actually we dont.
But maybe it still make sense.
@Sirupsen thoughts?
=> Allow not to configure semian for Mysql2

lib/semian/adapter.rb, lib/semian/mysql2.rb, lib/semian/redis.rb, test/mysql2_test.rb, test/redis_test.rb
Followup of https://github.com/Shopify/semian/pull/32
@Sirupsen and @csfrancis for review please.
=> Rename ResourceOccupied in ResourceBusy for correct :us:

lib/semian/mysql2.rb, lib/semian/protected_resource.rb, test/mysql2_test.rb
Fixes: https://github.com/Shopify/semian/issues/39
@fw42 @Sirupsen for review please.
=> Report MySQL connection errors to the circuit breaker

README.md
I'll be adding a section on how it works and how to pick good configuration later. For now I've just added standard Usage documentation.
@csfrancis @byroot
=> readme: initial overhaul

lib/semian/redis.rb
@Sirupsen @fw42 for review please.
Not sure if it's worth testing, it only appear after several reconnection attempts.
=> Also rescue Errno::EINVAL in Redis adapter because of an upstream bug

README.md
I've added a section on understanding Semian and provided a better intro. I think this, in conjuction with the RDOCs by @csfrancis, serve as a good starting point.
Once it's merged I'll throw the docs at some people and ask where they get stuck/have questions.
@byroot @csfrancis
=> readme: major overhaul

README.md, lib/semian.rb
@sirupsen This has a bunch of stylistic changes, you don't have to agree with all of them :). It's kind of hard to read in places and I tried to clear it up.
From the standpoint of a non-C developer, the terms `ECONNREFUSED` and `ECONNRESET` might be unfamiliar
"convergence time" is kind of vague
=> Some grammatical and stylistic changes in the README

LICENSE.md, semian.gemspec
=> this is under Shopify

Gemfile, scripts/install_toxiproxy.sh, semian.gemspec
@csfrancis @fw42 will fix your issues since it's compatible with v2.0.0rc1 which is what we run internally now.
=> toxiproxy: update to v2.0.0rc1

README.md
On Friday I was explaining Semian to @dalehamel, @dwradcliffe and @kirs. The question came up about when circuit breakers are useful and when bulkheads are. To explain the co-operation, we ended up drawing the graphs below on a whiteboard to explain how they work together. This explanation seemed like a useful addition to the README.
@Shopify/resiliency @BoGs @jacobbednarz
=> readme: explain co-operation between cbs and bulkheads

ext/semian/semian.c
Switch from tracking our semaphore indices manually, with static const ints, to using an enumerated type.
In my opinion, this is a C best-practice as this is what enumerated types are for. I hope this doesn't come off as a bike shed, as I think that there are legitimate technical reasons for using enumerated types in this instance.
First off, I think that the code becomes more readable as the concept of an index is abstracted - you're able to give the name of the semaphore you expect, and the fact that it is an index happens implicitly because of how enumerated types work.
This also somewhat future proofs this, as there's no need to update the "kNumSemaphores" variable manually, the convention of using the last value of an enum as the count will allow us to always know how many semaphores …
=> Switch to enumerated type for tracking semaphore indices

ext/semian/sysv_semaphores.c, ext/semian/tickets.c, test/resource_test.rb
Approved in https://github.com/Shopify/semian/pull/127 but accidentally merged into the wrong branch
=> Register all workers 2

CHANGELOG.md, lib/semian/version.rb
@jpittis @sirupsen @simon-shopify @csfrancis
=> Release version 0.7.4

CHANGELOG.md, lib/semian/version.rb
Diff: https://github.com/Shopify/semian/compare/349a32486539548502a68cb051c3024b8cfd3fe8...4a57c8ba7b7de8b73225121406f0d7f6227f641e
=> Version 0.7.8

lib/semian/redis.rb, test/redis_test.rb
If a Redis server runs out of memory (memory usage exceeds what's defined in `maxmemory`), the server will respond to certain commands with a `Redis::CommandError`. This PR makes it so that those errors are being treated as Semian resource errors, therefore opening the Semian circuit.
The idea is that a Redis server that is out of memory should (at least for writes) be treated similar to a Redis server that is completely down. The consequence of this PR is that the application that's using Semian sees those two errors similarly (in particular, our resiliency fallbacks in Shopify core will now catch those errors and correctly evaluate the specified fallbacks).
One thing that's not great about this is that (I think) only **writes** would previously fail while now writes will open the …
=> Redis::OutOfMemoryError resource exception

lib/semian/redis.rb, test/redis_test.rb
Follow-up to https://github.com/Shopify/semian/pull/172 (and https://github.com/Shopify/semian/pull/190).
=> Catch OOM errors from scripts

CHANGELOG.md, lib/semian/version.rb
Bump version to 0.8.4
Diff: https://github.com/Shopify/semian/compare/7d92da4d4ecb7de691ae62657e6a381a7a39331a...f097c40fdabd53f2a0c7f2887865c75a9315a5d1
=> Bump version to 0.8.4

CHANGELOG.md, lib/semian/version.rb
Includes https://github.com/Shopify/semian/compare/HEAD~3..master. I've also updated the changelog.
=> Bump to 0.8.5

CHANGELOG.md, lib/semian/version.rb
=> Bump to version 0.8.8

.travis.yml, ext/semian/circuit_breaker.c, ext/semian/semian.c, ext/semian/simple_integer.c, ext/semian/sliding_window.c, ext/semian/sliding_window.h, ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h, ext/semian/sysv_shared_memory.c, ext/semian/sysv_shared_memory.h, ext/semian/tickets.c, ext/semian/types.h, ext/semian/util.h, lib/semian/circuit_breaker.rb, scripts/cleanup_ipc.sh, test/circuit_breaker_test.rb, test/resource_test.rb, test/simple_integer_test.rb, test/simple_sliding_window_test.rb, test/simple_state_test.rb
This only puts locking around SimpleInteger, would like some 👀 before continuing because I'm not super confident about the approach. If it's ok then I can add locks to the circuit breaker and sliding window.
Ideally, the logic for semaphore set creation shouldn't be repeated, and I'm wondering if I should be pushing the locking down a layer. Don't know what 'the proper C way' is!
(this also includes #228)
=> WIP: Locks

ext/semian/sysv_semaphores.c
Retry `semop` and `semtimedop` syscalls in `perform_semop`. 
When `semop` and/or `semtimedop` system calls are interrupted by a signal, they are not automatically retried, resulting in failure to acquire/set semian resources. 
```
Semian::InternalError: error setting ticket count, errno: 4 (Interrupted system call)
```
=> Retry syscalls in perform_semop if interrupted

lib/semian/circuit_breaker.rb
It's useful to see which circuit is currently changing state!
=> Add circuit name to state transition log message

lib/semian/adapter.rb
Ref: https://github.com/Shopify/semian/pull/199#discussion_r223793757
Seems like there was concerns about the `cause:` argument compatibility, but while it was only recently documented it works as far back as MRI 2.3:
```
$ ruby -e 'p RUBY_VERSION; p((raise "foo", cause: "bar" rescue $!).cause)'
"2.3.7"
"bar"
```
=> Directly set the last error as cause rather than raise twice

README.md
This should help clear up some of the confusion on the configuration of the circuit breaker.
I would like to make an equivalent post for bulkheads too eventually.
=> Add configuration blog post to readme

CHANGELOG.md, lib/semian/version.rb
Only one minor change here: https://github.com/Shopify/semian/pull/266
Not sure if there's anything else that needs fixing
=> Release v0.10.2

CHANGELOG.md, lib/semian/version.rb
Push the new changes (https://github.com/Shopify/semian/pull/285) (#283) to a new minor version for the gem
=> Release v0.11.3

CHANGELOG.md, lib/semian/version.rb
https://github.com/Shopify/semian/pull/301
=> 0.11.5 bump

CHANGELOG.md, lib/semian/version.rb
* Fix: pass disable flag by patching new singleton method (#303)
=> 0.11.6 bump

lib/semian/version.rb
Releasing a tiny patch change to support Rails edge - https://github.com/Shopify/semian/pull/309
=> Release 0.11.9

semian.gemspec
Make sure semian gem include required files.
=> Update gemspec to include License, Changelog and Readme

CHANGELOG.md
=> Add changelog entry for 364

CHANGELOG.md, Gemfile.lock, lib/semian/version.rb
Release version of Semian that includes support for new Rails connection changes.
=> Release 0.13.2

.github/workflows/test.yml, Gemfile.lock, Rakefile, examples/activerecord_trilogy_adapter/00_circuit_minimal.rb, examples/activerecord_trilogy_adapter/03_circuit_open.rb
Update README about AR Trilogy and examples.
First examples with minimal steps to reproduce semians behaviour.
=> Provide examples how could be AR Trilogy is working
