ext/semian/semian.c, lib/semian.rb, lib/semian/resource.rb
This is just some simple preparatory work to bring circuit breaker in Semian.
Just to have more control about the API etc, I make the C use the Ruby constants instead of the other way around.
@csfrancis @Sirupsen for review please.
=> Refactor Semian to have more control on the ruby side

.travis.yml, Rakefile, lib/semian.rb, lib/semian/circuit_breaker.rb, lib/semian/mysql2.rb, lib/semian/protected_resource.rb, lib/semian/resource.rb, scripts/install_toxiproxy.sh, semian.gemspec, test/fixtures/toxiproxy.json, test/test_circuit_breaker.rb, test/test_mysql2.rb, test/test_semian.rb
For the fun I integrated it in Shipit: https://github.com/Shopify/shipit2/commit/10ee2cc8d0eec39f7c882b47b6e8693adcac998c
If must be manually enabled via:
```ruby
Semian::Mysql2.enable!([optional global settings])
```
And then individual connections can have their settings defined when the client is instanciated:
```ruby
Mysql2::Client.new(semian: {timeout: 42, ...})
```
Which mean that for rails app, it can be done from the `database.yml`
```ruby
production:
...
semian:
timeout: 42
```
A couple things:
- Again no more StatsD. I believe it's the integration application responsibility. However I'll see if Semian can provide a couple hooks to make it easier.
- I simply ported our custom code, but I think `connect` and `query` should be using the circuit breaker. The fallback would be to …
=> Initial attempt at Semian::Mysql2

Rakefile, ext/semian/semian.c, lib/semian.rb, lib/semian/circuit_breaker.rb, lib/semian/instrumentable.rb, lib/semian/mysql2.rb, lib/semian/protected_resource.rb, lib/semian/resource.rb, test/test_circuit_breaker.rb, test/test_instrumentation.rb, test/test_mysql2.rb, test/test_semian.rb, test/test_unsupported.rb
Here a very simple monitoring API for semian resources:
Usage example:
```ruby
Semian[:mysql_master].listen(:occupied) do |resource|
StatsD.increment('Shopify.mysql.semian.timeout', 1, sample_rate: 1, tags: ["resource:#{resource.name}", "total_tickets:#{resource.tickets}"])
end
```
The 3 events are:
- `:occupied`
- `:circuit_open`
- `:success`
@Sirupsen @fw42 @csfrancis for review please.
=> Monitoring api

lib/semian/circuit_breaker.rb, test/circuit_breaker_test.rb
Imagine the following circuit breaker scenario with `error_count=3` and `error_timeout=5s`:
Time     | Circuit  | Errors within duration
-----------|-----------|-----------------------------
t-6         | closed  | [t-6]
t-1            | closed  | [t-6, t-1]
t        | **closed**          | [~~t-6~~, t-1, t]
The **expected outcome at time `t` is that the circuit remains closed** because only one error at that time has happened within the past 5s. In the current implementation **the circuit would open**. See `test_sparse_errors_dont_open_circuit`.
In the current implementation we keep track of errors with counts:
```ruby
def increment_recent_errors
if error_timeout_expired?
@error_count = 0
end
@error_count += 1
@error_last_at = Time.now
end
def error_timeout_expired?
@error_last_at && …
```
=> circuit_breaker: use sliding window

lib/semian/protected_resource.rb, test/instrumentation_test.rb
@byroot, @Sirupsen 
I was discussing this with @Sirupsen, and I find `occupied` to be kind of an awkward word to use when there are no tickets available. This renames `:occupied` to `:busy`.
=> Rename :occupied to :busy

lib/semian/circuit_breaker.rb, lib/semian/protected_resource.rb, test/circuit_breaker_test.rb
@fw42 @Sirupsen for review please.
I don't think it belongs to Semian. Semian is for protecting datastore drivers etc, with_fallback can only be used at an higher level.
=> Get rid of with_fallback

lib/semian.rb, test/mysql2_test.rb, test/redis_test.rb
@fw42 @Sirupsen for review please.
The idea is to be able to discriminate semian errors based on which resource fired it.
=> Expose the semian identifier in AdapterExceptions

lib/semian/adapter.rb, lib/semian/redis.rb, test/redis_test.rb
@Sirupsen @fw42 
I feel bad about that one. I should have done it way earlier. Connection and query timeout should increment the circuit breaker count.
=> Consider Redis::BaseConnectionError in the circuit breaker errors count

lib/semian/adapter.rb, lib/semian/mysql2.rb, lib/semian/redis.rb, test/mysql2_test.rb, test/redis_test.rb
Followup to: https://github.com/Shopify/semian/pull/38
This will allow to discriminate errors coming from different Redises or MySQLs
@Sirupsen @fw42 for review.
=> Also tag natvie adapter errors with the resource identifier

Rakefile, ext/semian/extconf.rb, lib/semian.rb, lib/semian/platform.rb, test/semian_test.rb
Some processes that run offline actually don't benefit from semian, for instance processes that do maintenance by just moving a ton of resources around concurrently, they pretty much occupy  all the available tickets by design.
For those cases  I'm providing a way of disabling semian.
=> Adds a disable env var

.rubocop.yml, .travis.yml, Gemfile, Rakefile, ext/semian/extconf.rb, lib/semian.rb, lib/semian/circuit_breaker.rb, lib/semian/protected_resource.rb, lib/semian/resource.rb, lib/semian/unprotected_resource.rb, semian.gemspec, test/circuit_breaker_test.rb, test/helpers/background_helper.rb, test/instrumentation_test.rb, test/mysql2_test.rb, test/redis_test.rb, test/resource_test.rb, test/semian_test.rb, test/unprotected_resource_test.rb
No offense but @kyewei PRs have been ridded with totally non idiomatic code formatting and syntax (which is totally understandable for a Ruby newcomer).
I know it's not what is important, but it's hard to focus on real problems when it gets in the way.
The idea here is to enforce basic rules automatically, so that we don't have to waste time on PRs.
I took the rules from shipit-engine, with a couple changes. 
@fw42 @Sirupsen thoughts? I'm gonna be honest I don't want to debate any single rule, it's more a "take it or leave it" PR.
=> Style guide enforced on CI

lib/semian/mysql2.rb, test/mysql2_test.rb
Semian should not prevent MySQL rollbacks, otherwise queries that are made within a transaction can't get properly rolled back by things like ActiveRecord, because the rollback query also fails, which might keep transactions open for an unnecessary amount of time, causing database contention.
@tjoyal @camilo @Sirupsen @sroysen @byroot
=> allow rollbacks

.gitignore, lib/semian.rb, lib/semian/circuit_breaker.rb, lib/semian/protected_resource.rb, lib/semian/simple_integer.rb, lib/semian/simple_sliding_window.rb, lib/semian/simple_state.rb, lib/semian/unprotected_resource.rb, test/simple_integer_test.rb, test/simple_sliding_window_test.rb, test/simple_state_test.rb
Older closed PR is this: https://github.com/Shopify/semian/pull/56
Even older massive PR that we're trying to split is this (probably a bit outdated by this point): https://github.com/Shopify/semian/pull/54
Three structures are for holding the `@success`, `@state`, and `@sliding_window` of the `CircuitBreaker` class. 
They are now under `Semian::Simple`, and future SysV implementation will be under `Semian::SysV`. 
Issue that came up and may/may not have been addressed: 
* For methods in the classes that explicitly return `self` as the last line, its so things like `#<<` don't expose the inner array and leak the implementation, and instead return the appropriate wrapper class. Cascading still works: `wrapper_class_instance << 1 << 2`
* The `Atomic` prefix was removed since it is …
=> Extracted CircuitBreaker states into 3 structures

lib/semian/adapter.rb
If any options were specified and accessed earlier then upon subsequently attempting to create a resource it would find the already accessed options and skip creating the resource, instead returning the options hash which was then asked to `#acquire` and yielded something like:
NoMethodError: undefined method `acquire' for #<Hash:0x007fb7cae23090>
.../vendor/cache/ruby/2.1.0/gems/semian-0.3.0/lib/semian/adapter.rb:27:in `acquire_semian_resource'
.../vendor/cache/ruby/2.1.0/gems/semian-0.3.0/lib/semian/redis.rb:60:in `connect'
.../vendor/cache/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
.../vendor/cache/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
...
=> Fix semian resource memoization

README.md, lib/semian/net_http.rb, semian.gemspec, test/net_http_test.rb, test/test_helper.rb
^ What the title says. 
If `semian/net_http` is included in a rails server instance, then some sort of initialization like this has to occur:
In `http.yml`:
```yaml
development:
default:
tickets: 1
success_threshold: 1
error_threshold: 3
error_timeout: 10
...
```
In an initialization file somewhere:
```ruby
http_config = YAML.load_file("#{Rails.root}/path_to_file/http.yml")
Semian::NetHTTP.semian_configuration = proc do |host, port|
semian_identifier = "nethttp_#{host}_#{port}"
if !http_config[Rails.env].key?(semian_identifier)
[semian_identifier, http_config[Rails.env]["nethttp_default"]]
else
[semian_identifier, http_config[Rails.env][semian_identifier]]
end
end
Semian::NetHTTP.semian_configuration = proc do |host, port|
semian_identifier = "nethttp_#{host}_#{port}"
[semian_identifier, …
```
=> Net::HTTP Semian Adapter

test/net_http_test.rb
^ what it says.
The Toxiproxy ruby interface communicates over http to the daemon. When you combine `semian_identifier`'s in `test_use_custom_configuration_to_combine_endpoints_into_one_resource`, 3 errors are probably reached through the 'GET's, but since Toxiproxy shares the same circuit breaker state, `semian_identifier`: `nethttp_default`, it tries to communicate and triggers `Net::CircuitOpenError: [nethttp_default] Semian::OpenCircuitError`.
Small fix disables the adapter (returns `nil`) for connections to the Toxiproxy daemon.
This also explains why it triggers more failed tests after: since it was a `:down` call on the proxy, the call to bring it back up doesn't go through and further tests that reuse the same proxy fail.
Look it over and I suppose merge it into 0.4?
@Sirupsen …
=> Fix flakey test by ignoring toxiproxy when activating Net::HTTP

README.md, lib/semian/net_http.rb, test/net_http_test.rb
From investigating the issue with the flakey test, I found that if something like this occured:
```ruby
Net::HTTP.semian_configuration = proc { DEFAULT_SEMIAN_OPTIONS.merge(name: 'localhost_80') }
http = Net::HTTP.new('localhost', 80)
http.semian_resource.acquire {}
Net::HTTP.semian_configuration = proc { DEFAULT_SEMIAN_OPTIONS.merge(name: 'default') }
assert_equal 'nethttp_default', http.semian_resource.name #FAILS
```
This actually occurs when using the Toxiproxy ruby library for example. For communicating with the daemon, the ruby client does something to this effect: `Toxiproxy.http ||= Net::HTTP.new('localhost', 8474)`
The above fails because `@semian_resource` is cached. So I uncached it by checking to see if the `proc` changes and setting it to `nil` if it does. However, it then …
=> Net::HTTP resource invalidation fix

ext/semian/semian.c, test/resource_test.rb
@Sirupsen, @byroot 
This will automatically convert floating point ticket counts to integer values instead of raising `TypeError`.
=> Automatically convert T_FLOAT ticket count

semian.gemspec
@byroot 
Apparently rake 11 removes the `last_comment` method, which breaks Travis (via Rubocop) with:
```
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000000fc6520>
/home/travis/.rvm/gems/ruby-2.1.1/gems/rubocop-0.34.2/lib/rubocop/rake_task.rb:23:in `initialize'
/home/travis/build/Shopify/semian/Rakefile:4:in `new'
/home/travis/build/Shopify/semian/Rakefile:4:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```
This just forces us to use rake 10.
http://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11
=> Don't use rake 11

.travis.yml, lib/semian/net_http.rb, semian.gemspec
Ruby 2.3.0 has deprecated the `TimeoutError` const causing Ruby to issue some warnings.
```
lib/semian/net_http.rb:37: warning: constant ::TimeoutError is deprecated
```
Since this was listed as an alias for `Timeout::Error` seems safe(?) to propose it's removal.
Added Ruby 2.3.0 to the Travis builds to confirm.
=> Remove deprecated TimeoutError const

lib/semian/redis.rb, test/redis_test.rb
The redis client is a bit special because:
- `Redis.new` returns some kind of wrapper.
- The "real" client is in `Redis.new.client`
- So we have an delegator on `Redis#semian_resource` to `Redis::Client#semian_resource` to respect's semian contract.
The problem is that the redis "wrapper", during `pipelined` and similar block calls, replaces the `Redis::Client` instance by a `Redis::Pipeline` instance, and there is no way to access the real client anymore because it's just in a local variable. See: https://github.com/redis/redis-rb/blob/fd77358708920b3b7b76955eda22e8c89647aae5/lib/redis.rb#L2248-L2258
We knew about this error, I even put a descriptive comment about why we were memoizing the resource.
Where I dropped the ball is that if the first call ever to `semian_resource` is from …
=> Fix lazy aliasing of Redis#semian_resource

Gemfile, scripts/install_toxiproxy.sh, semian.gemspec
It's been a while that toxiproxy  server 2.0 and client 1.0 have been released.
FYI @Sirupsen
=> Use published version of the toxiproxy gem

test/net_http_test.rb
@casperisfine for review
After seeing CI failures on https://github.com/Shopify/semian/pull/87 which didn't seem relevant to that PR, I retried CI on master (https://travis-ci.org/Shopify/semian/jobs/143832816) and it failed the same way.
It looks like `TCPSocket.new(hostname, port)` was raising an exception when hostname is "localhost", so tried "127.0.0.1" and it seems to have fixed the error.
=> Fix CI connect errors on HTTP requests by using 127.0.0.1 for host

lib/semian/circuit_breaker.rb, lib/semian/protected_resource.rb, lib/semian/unprotected_resource.rb, test/circuit_breaker_test.rb
First draft for https://github.com/Shopify/semian/issues/86
The idea here is to remove any side effect `request_allowed?` might have, so that it's safe to call it from a threaded environment.
NB: The other circuit breaker methods stays unsafe and it's the adapter's responsibility to call them safely.
=> Make request_allowed? thread safe

lib/semian/mysql2.rb, test/mysql2_test.rb
Currently pings are not behind circuit breakers. They respect the default `read_timeout`, **which means that in stock Rails each request will take at least `read_timeout`, even if the data store is behind a circuit breaker**. This is because a connection is always pinged when it's checked out of the pool, see [`ActiveRecord::ConnectionPool#checkout_and_verify`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L776) and [`ActiveRecord::AbstractAdapter#verify!`](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L339).
Tagging Shopify people who've dabbled in AR:
@dylanahsmith @csfrancis @rafaelfranca @casperisfine
=> mysql: circuit break pings

lib/semian/mysql2.rb, lib/semian/version.rb
Observed that this isn't handled by the adapter when lowering MySQL `max_connections` counts during testing.
@Sirupsen @camilo @csfrancis @byroot
=> Also let "Too many connections" be a first class conn error

lib/semian.rb, lib/semian/rails.rb
Allows for things like:
```ruby
if ActiveRecord::Base.connection.semian_resource.request_allowed?
end
```
It's easily done with most semian adapters, but if you use Rails, the actual MySQL2 client is hard to get access to.
@fw42 @Sirupsen
=> Implement AR::AbstractAdapter#semian_resource

semian.gemspec
This moves the gemspec to use files on disk instead of files from git.
Only files in ext and lib folders are included, and only ruby, C source, and C headers are permitted.
Right now if you are refactoring, rake will base its file list off of the gemfile, which has it's list from git. This is quite annoying if you've added or removed files such that your file list is out of sync from git.
This change should cause it to always use the files on disk, which is a bit more intuitive.
=> Use glob instead of git for gemspec file list

ext/semian/semian.c, ext/semian/semian.h, ext/semian/semian_types.h
Part of https://github.com/Shopify/semian/pull/101
- Refactor semian includes into semian.h
- Refactor semian types into semian_types.h
Splitting larger omnibus refactor into more reviewable PRs
=> Refactor semian.c includes and types into header files

.travis.yml, scripts/install_toxiproxy.sh
Fixes https://github.com/Shopify/semian/issues/68
Allows us to run CI builds faster by not using the legacy infrastructure. In order to do this, we have to stop using sudo.
*Note:* The builds take around the same amount of time, but are able to be scheduled right away.
The only reason we "need" sudo right now is to install a deb, and the only thing that deb is doing is running a single binary as a service.
Rather than grab the deb and start the service, let's just grab the binary and run it in the background with nohup.
=> Don't require sudo for travis

ext/semian/resource.c, ext/semian/semian.c, ext/semian/semian.h
Here we refactor argument checks for resource initialization out into static methods.
The static methods also perform type casting to the desired type.
A potential bug was discovered, where permissions were being downcasted from long to int.
This has been repaired, and signatures have been adjusted to use long instead of int where required.
The type conversion is now happening in exactly one place.
It's easier to read the initialize_resource function with this checking out of the way.
This also asserts a contract that each argument should have a function that checks it for validity, and then casts it to the correct C type.
=> Check arguments for initialize_resource

ext/semian/semian.c
If we increase the size of the semaphore set, we will see errors.
This is because calls to read from the set require you to specify the
cardinality of the semaphore set. If this changes, the ID is invalid.
The solution here is to include the set cardinality in the key before
we SHA hash it.
=> Generate a unique semaphore key by including size of semaphore set

ext/semian/resource.h, ext/semian/semian.c, ext/semian/semian.h, ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h
This moves sysv_semaphore related operations into their own files.
The implementations from semian.c are moved to sysv_semaphores.c almost without changes.
Likewise, much of the prototypes from semian.h have been moved to sysv_semaphores.h. This also includes some macros and includes that are specific to sysv_semaphores.
The only thing I added was documentation above the function prototypes in sysv_semaphores.h
**note:* kInternalTimeout was replaced by #define INTERNAL_TIMEOUT because this was simpler than dealing with making this variable an extern.
=> Refactor semaphore operations

ext/semian/semian.c, ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h
Helpers to protect critical sections when operating on the semaphores directly (manipulating ticket counts)
Currently only one use, but will be needed for additional ticket management strategies (particularly, the upcoming quota strategy).
In another upcoming PR, i'll be cleaning up the ticket management and having this PR in place helps tidy that up.
=> Create sem_meta_lock and sem_meta_unlock

ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h, ext/semian/tickets.c, ext/semian/types.h
replace get_max_tickets with a more generic get_sem_val, to be used to retrieve the value of an arbitrary semaphore in the set.
The function has been refactored to accept a second parameter - the index to use.
I also moved the semian indices to be generated via a C pre-processor technique called "x macros".
**Before you run away screaming**, keep in mind that the x macro is a fairly elegant solution to keeping to data structures in sync in C, and is a standard pattern for **exactly** this type of application. 
The x macro is utilized to keep the enum symbols and strings in sync. This allows for us to easily print which semaphore is being operated on for debugging purposes, or any time we would like to "pretty print" a semaphore by ID.
=> Refactor get_max_tickets to be a more generic get_sem_val

ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h, ext/semian/tickets.c, ext/semian/tickets.h
I realized i was using the wrong include syntax for local headers.
I fixed it to use "" instead of <>, so we don't collide with any system files with the same names.
=> Fix header syntax

ext/semian/resource.c, ext/semian/sysv_semaphores.c
Refactor acquire_semaphore_without_gvl so that it is **always** using WITHOUT_GVL
```acquire_semaphore_without_gvl``` is refactored to be ```acquire_semaphore``` (which is what it actually does).
A new ```acquire_semaphore_without_gvl``` is defined that simply wraps  ```acquire_semaphore```, but always using ```WITHOUT_GVL```.
This way, the caller need not know about ```WITHOUT_GVL```, which it is already demanding when it issues ```acquire_semaphore_without_gvl```, as it's right in the name.
=> Refactor acquire_semaphore_without_gvl to always be WITHOUT_GVL

test/resource_test.rb
I found a bug in this test. Because the assertion doesn't happen in the main process, the results are always ignored.
I fixed this test so that it can actually fail.
Under the existing implementation, a forked process attempts to make an assertion.
The results of this minitest assertion will always be ignored by the parent process,
because the master process doesn't care about the exit status of the forked process.
To work around this, the exit status of the child process is used to determine if a
timeout has occured, and the assertion is run in the parent process, running the rest
of the test suite.
=> Fix the 'acquire_with_fork' test

.gitignore, .rubocop.yml, README.md, ext/semian/extconf.rb, ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h, ext/semian/tickets.c, ext/semian/tickets.h, ext/semian/types.h, lib/semian.rb, lib/semian/resource.rb, semian.gemspec, test/resource_test.rb
**Note:** This is still a work in progress - particularly I'm missing test coverage, but I'd like a preliminary review (low time investment) on the approach here. I want to make sure that it passes a basic "kick-the-tires" test before devoting more time to something I may potentially have to drastically change.
Specifically, I'm looking for:
* Things I've blatantly overlooked or misunderstood
* Design issues or shortcomings
* Edge cases that I've missed during testing
* Tests cases that I should add but haven't
This still contains some debug prints / reminders to myself, please ignore those.
For deploying this, I'd like to:
* Do a first round of review on the approach / tests as described above
* Ship existing semian changes as 0.6.3
* Finalize the review / acceptance of these changes
* …
=> Support quota based allocation strategy

ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h, ext/semian/tickets.c, ext/semian/types.h, lib/semian.rb, lib/semian/resource.rb, test/resource_test.rb
Allow for quota workers to pad the acquire timeout while workers are booting.
There is the possibility of timeouts when using the quota strategy while
workers are booting, since there are a small number of workers.
We can prevent spurious timeouts caused by a small number of tickets
during this period, by allowing for the acquire timeout to be padded.
We store the desired padding value as part of the resource structure.
Whenever the ticket count is updated (workers are registered), a SETVAL occurs that will write the ctime of the semaphore.
We can compare this value with the current time to see if we are within the QUOTA_BOOT_GRACE_PERIOD. If we are, we know to replace any configured timeout value with our padded value.
=> Allow a boot grace period using quota strategy

ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h, ext/semian/tickets.c, ext/semian/types.h, lib/semian.rb, lib/semian/resource.rb, test/resource_test.rb
Reverts grace periods, as they don't seem to solve the problem we were attempting to solve.
This reverts commit a5a8dce5e111123cad717d44dbf490ca7e33af14.
We believe that timeouts actually only happen when we transition between the static ticket and quota strategies, because the number of workers running under a static strategy aren't reflected as registered workers. We are going to ship a solution that will mitigate that.
=> Revert "Allow a boot grace period using quota strategy (#125)"

ext/semian/sysv_semaphores.c, ext/semian/tickets.c, test/resource_test.rb
Register all workers, regardless of if they are quota-based or static-ticket based workers.
Currently it's possible to have spurious timeouts when transitioning
between static and quota-based ticket allocation.
This is primarily a problem when switching from static to quota-based,
as there will be a large number of unregistered static-ticket based
workers, who will have a very small number of tickets as the
quota-ticket based workers boot and register.
By registering all workers, we can account for this issue.
During initialization, all workers will register themselves, rather than only quota-based workers.
=> Register all workers - not just quota workers

lib/semian.rb, lib/semian/protected_resource.rb, lib/semian/unprotected_resource.rb, test/circuit_breaker_test.rb, test/helpers/circuit_breaker_helper.rb, test/helpers/resource_helper.rb, test/protected_resource_test.rb, test/resource_test.rb, test/semian_test.rb, test/test_helper.rb, test/unprotected_resource_test.rb
Breaking the coupling of ProtectedResource from circuit breaker and bulkhead. To allow the ability to request a circuit_breaker or bulkhead independent of each other without breaking the path of processing. 
Fixes #95 
The protected resource will be registered but will only contain the resources that have been requested. Given you do not want a resource the code path will not execute and will allow the ability to interact based on the properties given in `acquire` or `register`.
=> Break the coupling between the protected resource and circuit breaker

lib/semian/mysql2.rb
During upgrade to Rails5, blocking mysql with toxiproxy returned `closed MySQL connection` which wasn't trapped here.
This PR should fix this.
=> Add closed connection to mysql errors

lib/semian/redis.rb
With @dalehamel's changes that allow a quota based on the number of workers which is automatically tracked by Semian (https://github.com/Shopify/semian/issues/98), it's paramount that a resource is registered as many times as there are workers operating on that resource. In forking web-servers (such as Unicorn) you may instantiate Redis clients _before_ `fork`ing, causing only `1` worker to be registered with Semian (in master), instead of `n`.
Since you _shouldn't_ do I/O in the master, we can fix this problem by lazily registering the resource the first time we do I/O. I've tested this by raising in `Semian.retrieve_or_register` and booting Unicorn for our app, and it was successful (i.e. it didn't retrieve or register Semian while booting).
I'd like to have a test for this but I don't …
=> redis: lazily instantiate client on first i/o

ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, lib/semian.rb, lib/semian/resource.rb, test/resource_test.rb
Add the ability to manually unregister a resource without deleting it
So that clients may choose to unregister a resource, for instance, in a parent process, and then re-register in a child process.
=> Add ability to manually unregister resources

ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, lib/semian/resource.rb, test/resource_test.rb
Expose the registered worker count to the ruby
The number of registered workers is extremely important to keep track of for the quota strategy. Exposing it to the resource allows for it to be emitted as a statsd metric very easily.
Essentially, this is just a standard accessor pattern.
=> Expose registered worker count to resource in rubyland

lib/semian/protected_resource.rb, lib/semian/unprotected_resource.rb, test/resource_test.rb
Expose registered_workers to resources through bulkheads.
Easier access, in line with other accessors.
=> Expose registered workers

ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h, ext/semian/types.h, lib/semian/resource.rb, test/resource_test.rb
Exposes the string representation of the hexadecimal sysvIPC key.
The Sysv IPC resource key is a portable hexadecimal string that uniquely identifies a particular resource.
The sysv IPC key is extremely useful for manually diagnosing and debugging via `ipcs` as it is portable across systems. I had previously been manually adding an `sprintf` on a regular basis in order to debug, so may as well make this a first class citizen
Some minor code reorganization, adding new members to the resource struct and passing it in and referencing it to the sysv_semaphore initializer.
=> Expose sysv IPC key to semian resource in ruby.

.rubocop.yml, ext/semian/resource.c, lib/semian.rb, lib/semian/adapter.rb, test/adapter_test.rb, test/helpers/adapter_helper.rb, test/resource_test.rb, test/test_helper.rb
Functionality to track references to resource consumers - instances of
semian adaptors - has been added. Any time an instance of a semian adaptor
retrieves a semian resource, it will register itself as a consumer of the resource.
Some situations will necessitate clearing all semian resource references without actually destroying the underlying resource.
We need to clear the reference both globally (from the list of semian resources) but also any references that semian consumers may have.
An example case would be if a semian resource were initialized by a parent process before forking. In order for each child to receive their own unique resource reference (so that worker registration is accurate), clearing all semian resource references before forking is necessary.
It is assumed that the …
=> Add ability to unregister all resources, and clear all semian_resources

ext/semian/resource.c, test/resource_test.rb
This fixes a bug with unregister where if unregister is not done with SEM_UNDO.
This can cause the worker count to be incorrect if the decrementing of the worker count is done from a parent process before forking, as it can decrement a value that was actually incremented by a child, causing this to never be incremented again because it will disappear when the parent exits.
The addition of SEM_UNDO will cause the parent to undo the deregistration when it exits, so that if it had taken a child's ticket it will return it when it exits.
Also, sem_meta_lock added to make this easier to reason about.
=> Prevent races while unregistering

ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, lib/semian/resource.rb, test/resource_test.rb
Add a helper to forcefully reset registered worker counts to zero.
In case if the worker count gets corrupted, this is safe to do for resources using static tickets.
This method would need to be manually invoked, and then the next time the workers restart they should correctly register themselves. semctl with SETVAL will clear the SEM_UNDO table, which should cause the next registration to proceed correctly.
This is only safe on resources that are using static tickets or for debugging / diagnostic purposes, and should not be called regularly.
=> Add helper to forcefully reset worker counts

lib/semian/mysql2.rb
During our gem bump of `mysql2` (to 0.4.5), we noticed that we weren't throwing any `Mysql2::CircuitOpenError` exceptions, since a new mysql exception message was being used: `MySQL client is not connected`.
cc @georgetzavelas @bibstha
=> Add new mysql connection error

lib/semian.rb, lib/semian/circuit_breaker.rb, lib/semian/protected_resource.rb, test/protected_resource_test.rb
Before now, `:name` was delegated to `Bulkhead`. Because both bulkheads and circuit breakers are now optional, it makes sense that `:name` lives in `ProtectedResource`.
Before this change, any attempt to grab a resources name if bulkheads were turned off would result in an exception.
I also added a test to make sure no one initializes a resource without a circuit breaker nor a bulkhead.
r: @sirupsen
=> change name delegator from bulkhead to circuit_breaker

.rubocop.yml, README.md, lib/semian.rb, lib/semian/circuit_breaker.rb, lib/semian/simple_integer.rb, lib/semian/simple_sliding_window.rb, lib/semian/simple_state.rb, test/simple_integer_test.rb, test/simple_sliding_window_test.rb, test/simple_state_test.rb
This is a stab at making Semian thread-safe for circuit breakers. It's not absolutely perfect, I'm sure—but I'm reasonably confident this is _good enough_ (and it's hard to do more than that with the limited concurrency tooling for Ruby).
This is coming out of a need for internal applications to adopt Semian for Sidekiq and Puma.
**How did you determine it's thread-safe?** I went through the logic from boot (creation of the resource) to checking the circuit breaker. The major culprit for races is around adding entries to the sliding window and trimming it. The rest of the races fixed are fairly harmless.
**Why didn't you make bulkheads thread-safe as well?** As outlined in the README, this is not trivial. However, I believe that for most applications—and especially threaded ones—circuit …
=> circuit_breaker: thread-safe by default

CHANGELOG.md, README.md, lib/semian/version.rb
- Includes the behaviour to [enable open circuiting on 5xxs conditionally](https://github.com/Shopify/semian/pull/149)
- Also includes the [configurable dependency hosts changes](https://github.com/Shopify/semian/pull/152)
r/ @albiere @sirupsen @jpittis
=> Minor version bump 0.7.1

CHANGELOG.md, lib/semian/protected_resource.rb, test/instrumentation_test.rb
This adds the time that it took to acquire the bulkhead to the success notification. The goal of this is to instrument how much contention there is on the tickets.
I merged it in the success notification, but I could also have added it to acquire in a separate benchmark notification.
=> Include time spend waiting for bulkhead in notification

ext/semian/sysv_semaphores.c
@ibawt PTAL
tl;dr i must have copy-pasta'd this, because this is clearly the wrong syscall that we are reporting here.
cc @sirupsen @csfrancis
=> Reflect the correct syscall in semctl error

README.md
Change readme regarding disabling bulkheads in threaded environments, by using the `bulkhead` flag instead of the `tickets` flag.
=> Update readme regarding disabling bulkheads in threaded environments

CHANGELOG.md, lib/semian/net_http.rb
This PR changes `Semian::NetHTTP` to use `prepend` instead of `alias_method_chain`-style method renaming. This is done so that it does not conflict with [`aws-sdk-core`, which also monkey-patches `transport_request`,](https://github.com/aws/aws-sdk-ruby/blob/85c08538c53cf5e76aa7d4b275a1d88b80fbb2ed/aws-sdk-core/lib/seahorse/client/net_http/patches.rb#L22-L71) when included in the "wrong" order.
The downside is that we lose the `raw_*` methods which are useful for instrumentation, though it is nothing that cannot be solved by requiring instrumentation code earlier.
=> Use prepend when monkey-patching Net::HTTP.

lib/semian/protected_resource.rb
Turns out there was an option to return the right format all along.
https://ruby-doc.org/core-2.2.1/Process.html#method-c-clock_gettime
=> Use built-in option to read the monotonic clock in ms.

ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, ext/semian/sysv_semaphores.c, ext/semian/types.h, lib/semian/protected_resource.rb, test/instrumentation_test.rb
This moves the benchmarking code for ticket acquisition as close as possible to the system call to eliminate anything that could artificially inflate the numbers.
=> More reliable way to measure wait time.

lib/semian/resource.rb
A recent change (#161) made ProtectedResource#acquire yield the amount of time during
which the thread was block acquiring the semaphore. This change updates
ProtectedResorce to do the same (with a value of 0).
=> Have resource consistently yield wait_time.

CHANGELOG.md, ext/semian/sysv_semaphores.c, ext/semian/tickets.c, ext/semian/tickets.h, ext/semian/types.h, test/adapter_test.rb, test/protected_resource_test.rb
A code change moved `sem_meta_unlock` outside of the protected scope. This PR brings it back inside.
=> Make sure internal semaphore release is protected.

README.md
Building and testing resilient ruby on rails applications blog post has been moved to the engineering blog. Updated the URL to reflect the change.
=> Update blog url from Shopify to Shopify Engineering blog

lib/semian/redis.rb, test/redis_test.rb
New versions of the Redis gem have `client` defined as the Redis CLIENT command itself.  The Redis client configuration is available as `_client`.  I've added a mock implementation to preserve compatibility with old Redis versions.
Old version of the code: https://github.com/redis/redis-rb/blob/3.3/lib/redis.rb#L10
New version of the code: https://github.com/redis/redis-rb/blob/b362cf23173bd2fea8b4cbd63bfff696fffbb84c/lib/redis.rb#L109
=> Update for Redis 4

.gitignore, README.md, Vagrantfile
This allows people to work on Semian from non-Linux machines.  The base image is Ubuntu Xenial, and Ruby 2.4.3 is installed from source using ruby-build.
Inside the image, Toxiproxy is not started because the deb package doesn't provide a systemd service.  This means toxiproxy-server has to be started before the tests can be run inside the virtual machine.
=>  Introduce a Vagrantfile with Ubuntu Xenial

lib/semian/circuit_breaker.rb, lib/semian/platform.rb, test/circuit_breaker_test.rb, test/semian_test.rb
For specific units of work (like LHM), we want to disable Semian. We've been running workers with `SEMIAN_SEMAPHORES_DISABLED=1` for that reason, but that option only disables the semaphores part. As I can see from LHMs logs it's still possible that Semian stops execution with circuit breaker:
```
param_queue_name: lhm	
payload: Started Job CrossPodJobs::PoddedLhmProcessingJob at 2018-03-06 ..., job_id=..., rev=ea71e5f, section=recurring_job
Parameters: {...}
[Semian::CircuitBreaker] State transition from closed to open. success_count=0 error_count=3 success_count_threshold=2 error_count_threshold=3 error_timeout=10 error_last_at="1520370901"
...
Job Error: Mysql2::CircuitOpenError: [mysql_shard_4] Semian::OpenCircuitError: drop trigger if exists `lhmt_del_payments_accounts` /* large …
```
=> Allow to disable circuit breaker

.travis.yml
2.1 is EOL, 2.2 will EOL :soon:.
Let's test on modern Ruby versions that Shopify runs on.
=> Test on modern rubies

.travis.yml, gemfiles/mysql2-0-4-10.gemfile, gemfiles/mysql2-0-5-0.gemfile, lib/semian/adapter.rb
We need to pass the message to `SemianError` not an Error object:
- When rescuing exception https://github.com/Shopify/semian/blob/4e15669c538d3671bfcb25c2edf7f9e29278da89/lib/semian/adapter.rb#L38-L40 we are passing the error to the SemianError constructor
- This was going to cause an issue at some point and it's now the case on mysql2 0.5.0. https://github.com/brianmario/mysql2/pull/632/files#diff-634fc29a00423da17966525049aa8877L62 because of this change
=> Pass in the error message when initializing a SemianError

CHANGELOG.md, lib/semian.rb, test/semian_test.rb
Unfortunately, I'm not sure how to test this.  :{
=> Provide more details when raising ArgumentError over missing options

lib/semian/redis.rb, test/redis_test.rb
This allows Semian to track DNS resolution failures during `connect`. With the `redis` gem, this manifests as a `SocketError`.
Unfortunately, `hiredis-rb` masks the error by raising a generic `RuntimeError` on any connection failure (including DNS resolution): https://github.com/redis/hiredis-rb/blob/2b46b19dda98ba487e61884087b60d692bd0753e/ext/hiredis_ext/connection.c#L193. Also, the vendor'd `hiredis` gem also obscures the resolution error: https://github.com/redis/hiredis/blob/3d8709d19d7fa67d203a33c969e69f0f1a4eab02/net.c#L330-L335.
I don't really like this solution, but it's the best I can come up with, without having to make a bunch of upstream PRs. I wasn't able to come up with a test for the `hiredis` path, because I couldn't determine if there's a way to use both `redis` and …
=> Handle DNS resolution failures on connect

README.md
Make the units (seconds) more clear in our readme.
cc @simon-shopify
=> Add the units (seconds) to explain timeout parameters

README.md, lib/semian.rb, lib/semian/adapter.rb, lib/semian/circuit_breaker.rb, lib/semian/mysql2.rb, lib/semian/protected_resource.rb, semian.gemspec, test/circuit_breaker_test.rb, test/mysql2_test.rb, test/test_helper.rb
When a circuit is busy (for those at Shopify, see https://github.com/Shopify/shopify/pull/164168) you may reduce a substantial amount of capacity if you have large timeouts (see https://github.com/Shopify/semian/pull/145). One way to circumvent this is to have very large `error_threshold` timeouts, as a multiple of your timeout. E.g. if your resource timeout is 30s, then an error_timeout of 30s will make sure you have 50% of capacity available, and 60s will make sure you have 25% available (assuming that the circuits trigger equally over the timeout period, which is not an unreasonable assumption in production). However, this has obvious drawbacks, making recovering from incidents take longer for the affected resource.
Instead, we can reduce the resource timeout in the `half_open?` state …
=> circuit: introduce half_open_resource_timeout

CHANGELOG.md, lib/semian/circuit_breaker.rb, lib/semian/simple_state.rb, test/net_http_test.rb, test/protected_resource_test.rb, test/simple_state_test.rb
The circuit maintains its state on `@state`. Before this change, the definition of `half_open?` was that `@state == :half_open`. This changes the definition of `half_open?` to that _either_ `@state == :half_open` or the error timeout window has passed—so we're effectively `half_open?`.
**Why not just get rid of `@state == :half_open`?** If the circuit stays in the `half_open` state a while, `error_timeout_expired?` is no longer possible to use, i.e. you can't remove that `open?` conditional easily, I don't think.
**Why do you need this?** I'd like to be able to add in Marginalia the state of the circuit further up the stack (since Marginalia works at the AR-level). However, with Semian patching the MySQL client (and not AR)—this information is not present that far up the stack. It makes …
=> circuit: half_open? returns true when about to transition

lib/semian/redis.rb, test/redis_test.rb
Follow-up to https://github.com/Shopify/semian/pull/172.
Fixes an oversight from the previous PR. This essentially makes it so that `OutOfMemoryError#semian_identifier` is a thing, which is necessary to properly integrate this type of error into Shopify core's fallback evaluation logic.
=> Make OOM an adapter error

lib/semian/redis.rb, test/net_http_test.rb
Redis error:
```
> e.message
"Error connecting to Redis on thisdoesnotresolve:16379 (SocketError)"
> e.cause
#<SocketError: getaddrinfo: Name or service not known>
```
net_http_test flaky test
> Could still reach the service on hostname #{hostname} port #{port} after #{time_to_wait}s
Adding `server.stop` makes sure the server is stopped. Will monitor to make sure it did fix the flakiness.
=> Fix flaky test

lib/semian/circuit_breaker.rb, test/circuit_breaker_test.rb
Seems like in https://github.com/Shopify/semian/pull/188 the calls to `log_state_transition(:half_open)` and `@successes.reset` were removed.
@sirupsen @pushrax
=> reset successes when half opening

lib/semian/circuit_breaker.rb, lib/semian/simple_state.rb, test/circuit_breaker_test.rb, test/simple_state_test.rb
Follow up on https://github.com/Shopify/semian/pull/192
- Test the logging from one state to another.
- Make `open` and `close` consistent with `half_open!`
- Use `Timecop.travel` without `Time.now`
=> Addressing comments from #192

.rubocop.yml, README.md, lib/semian/circuit_breaker.rb, lib/semian/net_http.rb, test/net_http_test.rb
The `half_open_resource_timeout` feature was introduced here https://github.com/Shopify/semian/pull/188 but only for mysql2. 
This PR adds it for the `net_http` adapter. `Net::HTTP` let us assign the timeout by using [`read_timeout=` ](https://github.com/ruby/ruby/blob/trunk/lib/net/http.rb#L769).
=> Add half_open_resource_timeout for net http

lib/semian/adapter.rb, lib/semian/circuit_breaker.rb, test/net_http_test.rb
Related to https://github.com/Shopify/cusco/issues/193
As of now, here's what a Semian error will look like while debugging:
error_class: `CircuitOpenError`
error_message: `[service.website.com] CircuitOpenError`
With this change, we would add the last error message to the error_message, it would become something similar to `CircuitOpenError caused by Net::ReadTimeout`
Let me know what you think.
=> Add last error message to circuit breaker

.travis.yml, gemfiles/hiredis-0-6.gemfile, lib/semian/redis.rb, test/redis_test.rb
Hi redis returns RuntimeError, but `#cause` always returns nil. This makes sure we support all the scenarios simply by to_s'ing the error an matching on that string which should cover all cases.
I've also added a gemfile to travis test matrix to make sure this never happens anymore.
=> Test hiredis on CI & fix resolve errors

.rubocop.yml, semian.gemspec, test/resource_test.rb
Three small tweaks to reduce the noise for CI.
* Bump development_dependency for thin to 1.7.2 remove `Fixnum` warning
* Capture stderr for test_initialize_with_float and explicit assert warning message
* Rename rubocop definition whose namespace has changed
This PR should have no effect on runtime.
=> Resolve CI warnings

lib/semian/circuit_breaker.rb, test/circuit_breaker_test.rb, test/helpers/circuit_breaker_helper.rb
We would like to avoid marking the circuit for specific errors that are naturally subclasses of an error that should mark the circuit. In particular, for GraphQL, any HTTP non-success is considered a "transport error" and should generally mark the circuit, but some 4xx statuses occur for non-operational reasons and should not mark circuits. The cleanest way to express this is with a "trait."
=> If an error responds to #marks_semian_circuits? don't mark the circuit if it returns false

lib/semian/protected_resource.rb, test/instrumentation_test.rb
We currently only emit a `success` event on the `acquire_bulkhead` method, this causes a problem when we want to deactivate the bulkheads and still keep track of the successes.
[Event](https://github.com/Shopify/semian/blob/47bee8756cc84a198073acc0e148baed1b57d6fa/lib/semian/protected_resource.rb#L41) on circuit open for `acquire_circuit_breaker`.
Success [event](https://github.com/Shopify/semian/blob/47bee8756cc84a198073acc0e148baed1b57d6fa/lib/semian/protected_resource.rb#L50) on `acquire_bulkead`.
I've added `if @bulkhead.nil?` to avoid emitting two successes.
Related graph that went to 0 once bulkhead were disabled:
=> Instrument success on `acquire_circuit_breaker`

CHANGELOG.md, lib/semian/version.rb
Bump the gem version to 0.8.7. Includes the #209 PR which fixes instrumentation for the acquire circuit breaker method.
=> Bump version to 0.8.7

lib/semian/redis.rb
The error message on OSX is actually different when the host can't be resolved.
```
SemianTest#test_redis_raises_resolve_errors
[Redis::ResolveError] exception expected, not
Class: <RuntimeError>
Message: <"nodename nor servname provided, or not known">
---Backtrace---
test/unit/semian_test.rb:80:in `block (2 levels) in <class:SemianTest>'
test/support/initializers/active_support_test_case.rb:56:in `block in assert_raises'
test/support/initializers/active_support_test_case.rb:56:in `assert_raises'
test/unit/semian_test.rb:79:in `block in <class:SemianTest>'
---------------
```
Since the test suite is all running on linux containers, this is hard to test reliably, so this is probably good enough for now 😓
=> Fix resolve errors when using hi-redis + OSX

lib/semian/mysql2.rb, test/mysql2_test.rb
A MySQL Semian resource can be a bad resource if the queries are taking a longer time to respond and are exceeding the timeout options configured in database.yml of the application. Under such scenarios instead of waiting for a longer time and increasing the request queue it is good to have a circuit breaker in place and fail faster.
In the current implementation a Semian resource is not marked as failed when there is a MySQL timeout for the query.
Sample error trace for a long running query looks like -
Mysql2::Error: [mysql_192.16.10.158:3306] Timeout waiting for a response from the last query. (waited 18 seconds): select sleep(30)
ActiveRecord::StatementInvalid (Mysql2::Error: [mysql_192.16.10.158:3306] Lost connection to MySQL server during query: select sleep(30)):
=> Including Timeout error for mysql2 adapter

.gitignore, lib/semian/instrumentable.rb, lib/semian/lru_hash.rb, test/grpc_test.rb, test/lru_hash_test.rb, test/mysql2_test.rb, test/redis_test.rb
Our current hypothesis is that on average, `clear_unused_resources` behaves like an amortized O(1) operation, rather than an O(n) one. Without a robust simulator, however, we need to collect some runtime data to disprove the hypothesis.
This PR adds to the `implement_lru_cache` branch by instrumenting the `lru_hash_gc` event with stats about the garbage collection operation.
This PR also changes the signature of the `notify` method to have `payload` as the final argument so we can pass arbitrary data to subscribers.
=> Instrument the LRU

README.md, lib/semian.rb, lib/semian/lru_hash.rb, test/lru_hash_test.rb
Implement a `max_size` in the LRU cache.
The data ([dashboard](https://shopify.datadoghq.com/dashboard/mzg-id4-5rp/semian-lru)) we're seeing from core suggests that the LRU cache has a p99 garbage collection time of 1.5ms, and that garbage collection is run quite frequently.
(Note: I'm not sure how frequently, but the average number of evictions is 5 while the average size of the cache is about 150 and we have to examine over 100 of them every time.)
This PR adds a `max_size` parameter with a sensible default based on what we've observed in core. It's my expectation that we'll do fewer garbage collections until the cache fills, and then amortize one large garbage collection. This should lead to better Semian performance on average.
=> Added a max_size to the LRU cache

.travis.yml, lib/semian/redis.rb, test/redis_test.rb, test/test_helper.rb
Ran into an issue today where DNS was down, and the message that we got was "Temporary failure in name resolution" (which is EAGAIN on getaddrinfo). This wasn't opening circuits, leading to cascading failure.
cc @inf-rno @stefanmb @daniellaniyo @csfrancis @hkdsun
=> 'Temporary failure in name resolution' is a DNS lookup failure

test/resource_test.rb
This test was really flaky on my local machine.
It happens when the worker gets the `TERM` signal before Semian has timed out (or acquired the resource). 
I've been watching this for a while and seen no more flakiness.
`watch -n 1 bundle exec ruby -I test --verbose test/resource_test.rb -n /test_acquire_timeout_override$/`
cc: @Shopify/servcomm
=> Flaky test: Wait an extra 100ms to allow Semian to timeout

.travis.yml
Use https://docs.travis-ci.com/user/languages/minimal-and-generic/#minimal for the builds
It speeds up CI by at least double digit seconds by skipping setting up `rbenv` and running `bundle install`. 
Since we are running everything in docker we don't need it
=> Use `language: minimal ` in travis

.gitignore, lib/semian/circuit_breaker.rb, test/circuit_breaker_test.rb, test/grpc_test.rb, test/instrumentation_test.rb, test/mysql2_test.rb, test/redis_test.rb
Send `:state_change` notifications when circuit breaker state changes.
This is useful to monitor the current Semian state in the simulator we're building.
We monitor state as a Prometheus gauge, with `closed=0` and `open=1`.
**Note**: This further shows the weakness of the notification API as currently written. The `(event, resource, scope, adapter, payload)` signature doesn't apply universally throughout the codebase. In this case, the `resource` is actually the `CircuitBreaker` instance, not the `ProtectedResource` like the other notifications. A better API would simply be `(event, payload)` where the payload is context dependent on the event type.
cc: @Shopify/servcomm
=> Notify on circuit breaker state transitions

Rakefile, ext/semian/resource.c, ext/semian/sliding_window.c, ext/semian/types.h, ext/semian/util.h, lib/semian/circuit_breaker.rb, lib/semian/protected_resource.rb, lib/semian/resource.rb, lib/semian/unprotected_resource.rb, test/circuit_breaker_test.rb, test/resource_test.rb, test/simple_sliding_window_test.rb
The code in #227 is not passing tests, because it forces an invariant on the `SlidingWindow` that entries be monotonic. This doesn't work, unfortunately, with host-based circuits, since individual processes perform a two-step operation of:
1. Getting the current timestamp, and
1. Pushing the timestamp onto the sliding window
These operations, performed without a lock, can be interleaved and violates the invariant.
I tried to make that operation atomic, but it breaks with tests that want to use `Timecop.travel` to modify the system time. Therefore, the only option I had was to relax the invariant.
This does change the runtime of the `reject!` function to Ω(n) from O(n). Given that n tends to be less than 100, even in host-based circuits with a large `scale_factor`, this shouldn't be a big …
=> Don't force sliding window entries to be monotonic

lib/semian/mysql2.rb, test/mysql2_test.rb
Fix: https://github.com/Shopify/semian/issues/211
@DougEdey and @cjgu just reported two similar nasty production incidents on tow different apps.
Long story short, after a legitimate connection error caused by a SQLProxy being moved around, the app would get unusable for dozens of minutes, and a gigantic amount of `Mysql2::CircuitOpenError` would be reported.
Then I noticed a very weird thing with these exceptions:
`Semian::OpenCircuitError` being cause by another `Semian::OpenCircuitError` makes no sense, because this means every attempt at reconnecting while the circuit is open, would push back the time at which it should close again. So if you enter such state, the only way to have the circuits close again would be to stop connections attempt for long enough.
Since this theory …
=> Fix a critical bug in MySQL2 adapter causing circuit breaker to almost never re-close

lib/semian/lru_hash.rb
- is related to https://github.com/Shopify/semian/pull/193
- attempts to fix a syntax error when Semian is loaded into older versions of Rails app.
- I'm working on a feature in the [Kit app](https://github.com/Shopify/kit) that requires making graphql calls and thought it would be nice if we could use [Cusco](https://github.com/Shopify/cusco). 
- Kit is running version `2.3.4` of Ruby, and can't upgrade yet as they're still on AWS.
- I added the Cusco gem to Kit, which has a dependency on Semian.
- When I fire up the Kit app with Cusco & Semian installed, the app hits a `SyntaxError` in [lru_hash.rb](https://github.com/Shopify/semian/blob/3fc9810c0f469e13a30cbbd7d3e867132f0e6977/lib/semian/lru_hash.rb#L156):
- Locally I changed the `try_synchronize` method to what's in this PR, mainly …
=> close block to avoid syntax errors on older versions

CHANGELOG.md, lib/semian/version.rb
Includes the half open resource timeout support for Redis added by https://github.com/Shopify/semian/pull/257.
=> Release v0.10.0

Gemfile, dockerfiles/semian-ci, gemfiles/hiredis-0-6.gemfile, gemfiles/mysql2-0-4-10.gemfile, gemfiles/mysql2-0-5-0.gemfile, lib/semian/lru_hash.rb, test/lru_hash_test.rb
Since https://github.com/ruby/ruby/commit/36da0b3da1aed77e0dffb3f54038f01ff574972b
Ruby checks more often for interupts in various enumerable methods,
so Hash#count for instance is no longer "atomic".
Because of this we need to syncrhonize before calling it on @table,
otherwise if multipel threads use the LRUHash, it migth fail with:
`can't add a new key into hash during iteration (RuntimeError)`
Credits goes to Alan Wu for figuring the bug.
=> Test ruby 2.7 and fix a thread safety issue

.devcontainer/Dockerfile, CHANGELOG.md, lib/semian.rb, lib/semian/grpc.rb, lib/semian/mysql2.rb, lib/semian/resource.rb, lib/semian/simple_sliding_window.rb, test/resource_test.rb
After updating an app to Ruby 2.7, I figured I should contribute to Semian by getting rid of these Deprecation warnings.
You can see these in previous [CI Runs](https://travis-ci.org/github/Shopify/semian/jobs/669129103#L357-L366) for Semian
I avoided doing any autoformatting/linting on these files in order to ensure that I applied the minimal set of changes
In Ruby 3.0, there's a change for Positional & Keyword arguments, you can read all the background [here](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) as it will do a much better job of explaining it than I will
~I went with the recommended solution of adding the `ruby2_keywords` gem [source](https://github.com/ruby/ruby2_keywords) and …
=> Fix positional/keyword arguments deprecation warnings for Ruby 2.7+

lib/semian/grpc.rb
They are visible in the semian test suite:
```
/usr/local/bundle/gems/grpc-1.28.0/src/ruby/lib/grpc/generic/service.rb:170: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/app/lib/semian/grpc.rb:82: warning: The called method `request_response' is defined here
/usr/local/bundle/gems/grpc-1.28.0/src/ruby/lib/grpc/generic/service.rb:185: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/app/lib/semian/grpc.rb:97: warning: The called method `bidi_streamer' is defined here
/usr/local/bundle/gems/grpc-1.28.0/src/ruby/lib/grpc/generic/service.rb:175: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call …
```
=> Fix Ruby 2.7 warnings in GRPC adapter

lib/semian/grpc.rb
Reverts Shopify/semian#269
I made a mistake, the issue wasn't actually in semian, I got confused because we have multiple layers of instrumentation on these methods.
The issue was actually in grpc and was fixed 2 weeks ago: https://github.com/grpc/grpc/commit/3e17411774d81b0371375d729b1166994854212e#diff-37292ab4014737ea90165c478a9a0e50
=> Revert "Fix Ruby 2.7 warnings in GRPC adapter"

README.md
Closes #253 
The old example made an assumption that the resource in question is a bulkhead (referencing tickets), when in some cases the resource will only be protected by a circuit breaker. This feels like a minimal example that will give ALL the event types, with reasonable tags. This is probably too many metrics (for most uses, `circuit_open` and `busy` is probably enough...) but is better than broken?
Tested this locally and it seems to work
=> Update README monitoring example

ext/semian/semian.c, ext/semian/sysv_semaphores.h
Without doing this the GC could move the objects returned by
rb_const_get and make Semian's globals point to unexpected objects on
the heap.
No tests here because usually compaction bugs are hard to trigger reliably. I'm trying to trigger them in https://github.com/Shopify/semian/pull/274 though. If it goes well maybe we should include that as a best-effort regression test.
=> Fixes for GC.compact

lib/semian/mysql2.rb, test/mysql2_test.rb
The current Semian behaviour will let [certain allow-listed MySQL queries to go through](https://github.com/Shopify/semian/pull/60), even if we don't have tickets -- but the existing matches are incompatible with using the [Marginalia gem set to `prepend_comment`](https://github.com/basecamp/marginalia/blob/7bf7ec89e18cd4849cd43c24ed931d341363665c/lib/marginalia.rb#L52).
This PR adds extra regular expressions to catch this particular case. We still need to anchor on either `\A` or `\z` because otherwise we would match allow-listed words when they appeared in the body of queries.
=> Allow MySQL queries through Semian regardless of position

README.md
Really tiny fix: The old URL was not working, so update with the new.
=> Minor fix: Update url for docker ipc reference

lib/semian.rb, lib/semian/resource.rb
I'm trying to rollout a major infrastructure change on an app, and among other things it involve a changed process UID. Because of this, during rollout I get some Semian permission errors:
```
gems/semian-0.10.6/lib/semian/resource.rb:14:in `initialize_semaphore': semget() failed, errno: 13 (Permission denied) (Semian::SyscallError)
```
I could try to change the permissions on every single resource, but I'd feel safer with a global configuration.
=> Introduce Semian.default_permissions

lib/semian.rb, lib/semian/resource.rb, test/resource_test.rb
I'm trying to rollout a major infrastructure change on an app, and among other things it involve a changed process UID. Because of this, during rollout I get some Semian permission errors:
```
gems/semian-0.10.6/lib/semian/resource.rb:14:in `initialize_semaphore': semget() failed, errno: 13 (Permission denied) (Semian::SyscallError)
```
Because of this I'd like to change the key of all our semaphores. 
`Semian.namespace` can be assigned a string that will be prefixed to all semaphores (before the hashing)
=> Add Semian.namespace to flush all resources

lib/semian/mysql2.rb
The mysql2 gem will only raise a `MySQL client is not connected` exception if [`CONNECTED(wrapper)` evaluates to false](https://github.com/brianmario/mysql2/blob/e2503dc6e8ad02f8c2f4fc71006f9840694e319c/ext/mysql2/client.c#L37-L39). In order to evaluate if the client is still connected, the [`CONNECTED` macro](https://github.com/brianmario/mysql2/blob/e2503dc6e8ad02f8c2f4fc71006f9840694e319c/ext/mysql2/client.c#L29-L33) will check the member contents of the NET struct [defined in libmysqlclient](https://github.com/mysql/mysql-server/blob/ee4455a33b10f1b1886044322e4893f587b319ed/include/mysql_com.h#L859-L866). Since `CONNECTED` only checks the local values stored in a struct, this check should resolve almost instantly.
If the `MySQL client is not connected` error fails fast, then I don't …
=> Remove fast failing MySQL connection error

CHANGELOG.md, lib/semian/version.rb
Only one minor change included in this release https://github.com/Shopify/semian/pull/282
I initially attempted to pin core's semian version to latest master, but had troubles with in-repo gem version consistency. Instead of testing the changes in core before publishing a version to rubygems, I plan to upload a new release to rubygems directly, then run `bundle update` in core and sfr
=> Release v0.11.2

README.md, lib/semian.rb
I've had a few instances of confusion around the interaction between error_timeout and error_threshold.
This simple update to the read-me will help but I can still see how this interaction is unintuitive. 
Perhaps it's time we also update error_threshold to work indefinitely despite the time between errors, and only reset the counter on success.
=> Resolve common misconception about error_threshold in the Readme

lib/semian/circuit_breaker.rb, test/circuit_breaker_test.rb, test/helpers/circuit_breaker_helper.rb
This PR will help address: https://github.com/Shopify/shopify-proxysql/issues/129
We are seeing elevated semian errors in core whenever we deploy to ProxySQL. I was unable to find any logs in splunk that noted what caused the circuits to open. This is possibly because the application code that receives the `CircuitOpenError` exception is not choosing to log the error message.
We need to be able to see what errors are causing the circuit to open, so I'm logging the `last_error.message` whenever the state is changed to `open`.
=> Log last error message on circuit breaker state transition

lib/semian.rb
This just corrects the spelling of `successful` on line 65 of `lib/semian.rb`
=> Fix for typo in semian.rb

lib/semian.rb
Hi, this is just a fix for typo, from `ciruit` to `curcuit`.
=> Fix typo of "circuit"

Gemfile, lib/semian/net_http.rb, test/net_http_test.rb
In opentelemetry we already implement our own retry mechanism with exponential backoff. Hence we want a way to disable semian temporarily for specific code blocks, to avoid seeing custom errors and overhead of semian.
My intuition is that having ability to disable semian for specific code path has usecases.
=> feat: add force disable semian

lib/semian/net_http.rb, test/net_http_test.rb
I goofed and earlier approach in #301 doesn't work. https://github.com/ruby/ruby/blob/1f4af993835219efa8feaf76a0b36252028691f1/lib/net/http.rb#L654 - http class has its `self.new` definition. This should patch the correct method, but I am a little bit apprehensive to use `instance_variable_set`
=> Fix disable flag

.devcontainer/docker-compose.yml, .github/workflows/main.yml, lib/semian/redis.rb, test/redis_test.rb
Connect Reset by Peer is a fast failing error and should not cause an open circuit, unfortunately the Redis gem bundles `ECONNRESET` along with a few other errors as `Redis::ConnectionError`.  This PR implements the `marks_semian_circuits?` method in the Redis::ConnectionError class and checks the error message to determine if the error is an ECONNRESET.  If it is then we don't mark this as a semian failure. 
This PR also update version of toxiproxy used in tests to 2.3.0 which supports a connect reset toxic.
=> Don't open the circuit on redis connection reset

.gitignore, Gemfile, Gemfile.lock, semian.gemspec
Current broken tests: https://github.com/Shopify/semian/runs/6526541521?check_suite_focus=true
Last success tests: https://github.com/Shopify/semian/runs/6229616802?check_suite_focus=true
The last compatible version was redis-client 0.2.0.
Move development dependencies to Gemfile.
Update gitignore to have Gemfile.lock.
It would allow to test gem against specific versions for dependencies.
Possible solution to check https://github.com/redis-rb/redis-client/blob/78c7932c28023ce8e1b9d64a04bd831cce539543/hiredis-client/lib/hiredis-client.rb
=> Tests are broken for latest redis-client

.devcontainer/docker-compose.yml, .github/workflows/main.yml, docker-compose.ci.yml
Update Github actions to use latest version of toxiproxy.
=> Bump toxiproxy to v2.4.0

.devcontainer/docker-compose.yml
Make sure there is possobility to spin Codespace[^1].
Remove mount ~/.gitconfig, as it is missing in Codespace.
Device: MacBook Air M1
1. Visit https://github.com/shopify/semian
2. Create a branch: "codespace"
3. Click on Code -> Codespace (tab) -> Create codespace on "codespace"
4. Open in VSCode local
5. Open Terminal and invoke:
```shell
$ bundle install
$ bundle exec rake build
$ bundle exec rake test
```
[^1]: [Codespace](https://code.visualstudio.com/docs/remote/codespaces)
=> Make codespace work

.github/workflows/test.yml, lib/semian.rb, test/adapter_test.rb, test/test_helper.rb
Tests are not passed in first try.
Set SEED to last successful passed tests.
Setup retry to the Github actions to run 3 times max.
Also updated test `TestSemianAdapter#test_unregister` - changed the resource name in tests to be uniq: from `:testing` to `:testing_unregister`
- Run 4 times tests: https://github.com/Shopify/semian/runs/6561304607?check_suite_focus=true
- Once https://github.com/Shopify/semian/runs/6561420204?check_suite_focus=true
=> Stablize running tests in CI

semian.gemspec
Add links to show on rubygems. It makes automated dependency management easier.
=> Add gemspec metadata

CHANGELOG.md, README.md
Release a new minor version, due to the numerous changes to support quota-based worker allocation. We now have dogfooded all of this code internally and it works as expected.
Fixes https://github.com/Shopify/semian/issues/133
=> Bump 0.7.0

.github/workflows/test.yml, README.md, Rakefile
Allow to split tests in batches and run.
I could not find a gem for it, so create a new single task base on Rake::TestTask
Currently it does not give huge boost, because I refactored github workflows and those already had improved test performance from 13 mins to 4 mins:
- https://github.com/Shopify/semian/pull/322
- https://github.com/Shopify/semian/pull/327
It requires two environment variables:
* *TEST_WORKERS* - Total number of workers or batches. It uses to identify a total number of batches, that would be run in parallel. Default: 1
* *TEST_WORKER_NUM* - Current worker id. The value is between 1 and *TEST_WORKERS*
```shell
$ bundle exec rake test:parallel TEST_WORKERS=5 TEST_WORKER_NUM=1
```
- [test-queue](https://github.com/tmm1/test-queue)
- …
=> Run test in batches

test/grpc_test.rb
close https://github.com/Shopify/semian/issues/315
=> #315 fix: slow gRPC test by setting default client timeout

Gemfile, Gemfile.lock
Shipit could not install grpc 1.47.
Reverting for stable version.
Recently I found that tests in CI/CD are failing related to GRPC. 
This PR should fix them all.
=> Freeze grpc version 1.46.3

Gemfile, Gemfile.lock, lib/semian/rails.rb, test/rails_test.rb, test/test_helper.rb
The refactoring in https://github.com/rails/rails/pull/44591 we started
seeing errors like `NoMethodError: undefined method 'semian_resource'
for nil:NilClass` coming from Semian. While this is called from
shopify/shopify, the `connection` that's `nil` is the one in the
`rails.rb` monkey patch.
After debugging with matthewd we found that Semian is relying on the
previous connection being available, whereas the new AR behavior means
it might not be.
To fix this we can memoize the `semian_resource` on `connection` in the
adapter, and then when the connection is reset or disconencted, set
`semian_resource` to `nil` and grab the new connection instance next
time we need it.
In addition to these changes I decided to add `activerecord` as a
development dependency to the gemspec so that we are …
=> Handle new Rails connection changes

Gemfile, Gemfile.lock, lib/semian/redis.rb, lib/semian/redis/v5.rb, lib/semian/redis_client.rb, test/redis_test.rb
Since 5.0 use redis-client under the hood, for the most part we only need to translate errors and delegate a few methods.
Closes #385
=> Redis 5.0 support

lib/semian/mysql2.rb, test/adapters/mysql2_test.rb
When reconnecting, Active Record's `MySQL2Adapter` closes the old connection, but keep the old connection around:
```ruby
def active?
!!@raw_connection&.ping
end
def connect
@raw_connection = self.class.new_client(@connection_parameters)
end
def reconnect
@raw_connection&.close
connect
end
```
So if that reconnection attempts fail, we are left with a closed connection in `@raw_connection`.
The problem is that if the circuit breaker was open, before closing again we move to `half-open` state, meaning we open again on the first failure.
Since before reconnecting `Mysql2Adapter` does try to ping the existing connection, we end up reopening the CB immediately because we called `ping` on a closed connection. 
Either way it makes no sense to report a failure in such case, as a closed connection …
=> Pinging a closed connection shouldn't be considered a failure

CHANGELOG.md, ext/semian/resource.c, test/semian_test.rb
Bulkhead require settings `:tickets` or `:quota`.
Error message suggested to add `:ticket`,
and it is not valid option.
There are examples to use `:tickets` [^1]
New message:
```
Semian configuration require either the :tickets or :quota parameter, you provided ...
```
[^1]: [Configuration](https://github.com/Shopify/semian#configuration)
=> Typo in error message in bulkhead settings

.devcontainer/docker-compose.yml, README.md
Set environment variable DEBUG to be enabled by default in container.
DEBUG environmnet is used in native extention to print debug infromation
of semaphors.
=> Enable DEBUG mode for development container.

CHANGELOG.md, ext/semian/sysv_semaphores.h
Bulkheading could be used in forks.
Add process id in the log message.
Old message: `lock 1, tickets: 1 configured: 2, registered workers 1`
New message: `[pid=123][semian] semaphore values lock 1, tickets: 1 configured: 2, registered workers 1`
=> Update debug message for resource (bulkheading)

CHANGELOG.md, lib/semian.rb, test/adapter_test.rb
When errors are created from other errors messages they might already have a semian identifier in their message
=> Avoid chaining duplicated semian identifiers in error messages

.devcontainer/docker-compose.yml, CHANGELOG.md, ext/semian/sysv_semaphores.c, ext/semian/sysv_semaphores.h, test/resource_test.rb
In debug mode there is an unexpected exception for tests.
THe function to print semaphores could not access to the resource and raise exception.
The observability should not produces exceptions and ignore errors.
```shell
$ DEBUG=1 bundle exec rake clean build
$ DEBUG=1 bundle exec ruby -Itest test/resource_test.rb -n test_destroy
[pid=1345][semian] semaphore values lock: 1, tickets: 0 configured: 0, registered workers: 0
[pid=1345][semian] semaphore values lock: 0, tickets: 0 configured: 0, registered workers: 1
F
Finished in 0.001262s, 792.3403 runs/s, 792.3403 assertions/s.
1) Failure:
TestResource#test_destroy [test/resource_test.rb:393]:
[Semian::SyscallError] exception expected, not
Class: <Semian::InternalError>
Message: <"error getting value of SI_SEM_LOCK for sem 131097, errno: …
```
=> DEBUG mode broke tests

CHANGELOG.md, README.md, lib/semian.rb, lib/semian/lru_hash.rb, lib/semian/protected_resource.rb, lib/semian/unprotected_resource.rb, test/helpers/time_helper.rb, test/lru_hash_test.rb, test/test_helper.rb, test/time_helper_test.rb
Resource updated_at used only for LRU cache to clean unused resources.
There is no need in keeping timestamp.
Sidecar:
Implement basic travel time helper to cover Monotonic clocks.
=> Replace Time.now with monotonic in lru cache and resource update

.rubocop.yml, examples/net_http/05_circuit_in_threads.rb, examples/net_http/06_circuit_in_fork.rb, examples/net_http/11_bulkhead_in_forks.rb, examples/net_http/12_bulkhead_quotes_in_forks.rb
Update examples to limit expected expectations and mark lines that should not be reached.
Replaced some rescue to single errors, to not cover to many problems.
Add lines to bulkhead examples to make sure script finished with unsuccess,
if thread or fork got exception.
Extract changes from https://github.com/Shopify/semian/pull/441/
=> Tune examples to cover some cases

.rubocop.yml, test/adapter_test.rb, test/circuit_breaker_test.rb, test/helpers/resource_helper.rb, test/instrumentation_test.rb, test/protected_resource_test.rb, test/resource_test.rb, test/semian_test.rb, test/test_helper.rb, test/time_helper_test.rb
Introduce semian resources clean up in ResourceHelper.
Update test `test_permissions` to make sure there is at least single line in semaphors.
Extract from https://github.com/Shopify/semian/pull/441
=> Standardize cleans up

.rubocop.yml, Gemfile, Gemfile.lock, gemfiles/grpc.gemfile, gemfiles/grpc.gemfile.lock, gemfiles/mysql2.gemfile, gemfiles/mysql2.gemfile.lock, gemfiles/net_http.gemfile, gemfiles/net_http.gemfile.lock, gemfiles/rails.gemfile, gemfiles/rails.gemfile.lock, gemfiles/redis_5.gemfile, gemfiles/redis_5.gemfile.lock, gemfiles/redis_client.gemfile, gemfiles/redis_client.gemfile.lock, test/adapters/net_http_test.rb, test/adapters/redis_client_test.rb, test/adapters/redis_test.rb, test/circuit_breaker_test.rb, test/test_helper.rb
NetHTTP setup method to clean all resources.
Remove usage of Timecop in redis adapaters.
Update circuite breaker tests to have initialization of resource in multiple lines.
=> Update tests to have less collisions of resources and remove Timecop

.devcontainer/Dockerfile, .github/workflows/analysis.yml, .github/workflows/dependencies.yml, .github/workflows/test.yml, CHANGELOG.md, Gemfile, Gemfile.lock, dockerfiles/semian-ci, gemfiles/grpc.gemfile.lock, gemfiles/mysql2.gemfile.lock, gemfiles/net_http.gemfile.lock, gemfiles/rails.gemfile.lock, gemfiles/redis_4.gemfile.lock, gemfiles/redis_5.gemfile, gemfiles/redis_5.gemfile.lock, gemfiles/redis_client.gemfile.lock
Add ruby 3.2 to the list of ruby versions to check tests against.
Upgrade hiredis-client to support ruby 3.2
=> Support Ruby 3.2

test/resource_test.rb
In tests used lru clean table with Mutex in fork process on exit.
It is not supported anymore and could be removed https://bugs.ruby-lang.org/issues/14222.
Sample exception:
```
Class: ThreadError
Message: can't be called from trap context
---Backtrace---
lib/semian/lru_hash.rb:110:in `synchronize'
lib/semian/lru_hash.rb:110:in `delete'
lib/semian.rb:231:in `unregister'
test/resource_test.rb:67:in `block in test_unregister_past_0'
```
Could not run https://github.com/Shopify/semian/blob/e1252f57da51e0c0c44fb4cae24063da4ae0b3b9/lib/semian/lru_hash.rb#L110 inside `Signal.trap`.
=> Remove unsupported way to run callbacks on signal

lib/semian/activerecord_trilogy_adapter.rb, test/adapters/activerecord_trilogy_adapter_test.rb
During working with Trilogy adapter,
found that `semian` key removed from the original Hash. 
Update adapter to use copy of input structure, instead of modify the object it self.
Example how to reproduce the problem:
```ruby
SEMIAN_PARAMETERS = {
circuit_breaker: true,
success_threshold: 1,
error_threshold: 3,
error_timeout: 3,
bulkhead: false,
}
configuration = {
adapter: "trilogy",
username: "root",
host: ENV.fetch("MYSQL_HOST", "localhost"),
port: Integer(ENV.fetch("MYSQL_PORT", 3306)),
database: "mysql",
semian: SEMIAN_PARAMETERS,
}
adapter = ActiveRecord::ConnectionAdapters::TrilogyAdapter.new(configuration)
adapter.execute("SELECT 1;")
adapter = ActiveRecord::ConnectionAdapters::TrilogyAdapter.new(configuration)
adapter.execute("SELECT 1;")
```
=> Make sure AR Trilogy adpater does not modify input

test/adapters/activerecord_trilogy_adapter_test.rb, test/adapters/mysql2_test.rb, test/adapters/redis_client_test.rb, test/adapters/redis_test.rb, test/helpers/background_helper.rb, test/protected_resource_test.rb, test/test_helper.rb
Closes: https://github.com/Shopify/semian/issues/471
Many test cases would define `teardown` without calling super so we were never killing threads...
It's better to use `before_teardown` anyway, and it's less popular so less likely to be overriden without a super.
This is very likely to be the cause of the crash we've seen at https://github.com/Shopify/semian/actions/runs/4122969863/jobs/7120418231
Co-Authored-By: @adrianna-chang-shopify
=> BackgroundHelper: avoid leaking threads

.devcontainer/Dockerfile, Rakefile, scripts/benchmarks/flamegraph.rb, scripts/benchmarks/lru_benchmarker.rb, scripts/benchmarks/net_http_acquire_benchmarker.rb
Add function to run benchmark against HTTP requests
for different Semian gem versions and git commits.
Add possibility to generate flamegrpahs:
```
rake flamegraph
```
Run different benchmarks: 
```
rake benchmark
```
Sample charts generated in https://github.com/Shopify/semian/issues/458#issuecomment-1405049992
=> Benchmark and performance review between versions

lib/semian/activerecord_trilogy_adapter.rb
The gem has been upstreamed to Rails edge, so
"active_record/connection_adapters/trilogy_adapter" might be defined by Rails itself.
=> Do not require "activerecord-trilogy-adapter"

.github/workflows/test.yml, gemfiles/rails_mysql2.gemfile, gemfiles/rails_mysql2.gemfile.lock, gemfiles/rails_trilogy.gemfile, gemfiles/rails_trilogy.gemfile.lock, test/adapters/rails_mysql2_test.rb, test/adapters/rails_tests.rb, test/adapters/rails_trilogy_test.rb
Follow-up to #486 
Since the adapter is in Active Record now, we can test Trilogy through Active Record too. So I just extracted the rails tests and used them both for the mysql2 and trilogy adapter.
Actually at first, I thought maybe the `semian/rails` code isn't too related to the specific adapter, so maybe there's no need to test it for each adapter/client semian supports, but then I saw the code from https://github.com/Shopify/semian/pull/395 which is specific to mysql2.
By adding a share test we could see the special case made for Mysql2 and reproduce it for Trilogy, but looking more into it, I don't think it's ever used:
```
>> ActiveRecord::ConnectionAdapters::Mysql2Adapter.method(:new_client)
=> #<Method: ActiveRecord::ConnectionAdapters::Mysql2Adapter.new_client(config) …
```
=> Also test trilogy adapter through activerecord

lib/semian/activerecord_trilogy_adapter.rb
Followup from https://github.com/Shopify/semian/pull/486
From https://github.com/rails/rails/pull/48054, `#execute` removes the support the `async` keyword parameter.
=> Remove Trilogy adapter's async keyword parameter in execute

CHANGELOG.md, Gemfile.lock, lib/semian/version.rb
Includes https://github.com/Shopify/semian/pull/494
Ensures Semian Trilogy Adapter works correctly with Rails edge.
=> Release v0.19.1

CHANGELOG.md, gemfiles/activerecord_trilogy_adapter.gemfile.lock, lib/semian/activerecord_trilogy_adapter.rb, test/adapters/activerecord_trilogy_adapter_test.rb
See https://github.com/Shopify/semian/pull/497
This PR ensures that `ActiveRecord::AdapterTimeout` errors are handled for the AR Trilogy Adapter. As of https://github.com/rails/rails/pull/48272/commits/785f65680b55a33e02cd5614e709b99b1fe6218b, TimeoutErrors are translated to AdapterTimeout errors in Rails. As such, we no longer need special handling in `#acquire_semian_resource` for such errors.
This commit also ensures that ActiveRecord::ConnectionFailed errors are classified as resource exceptions. These are network-related exceptions and should be handled by Semian. I've added a corresponding test.
cc @casperisfine @etiennebarrie
=> AR Trilogy Adapter: Handle AdapterTimeout and ConnectionFailed errs

CHANGELOG.md, ext/semian/extconf.rb
OpenSSL isn't located on standard paths on my Linux machine and thus I can't get Semian gem to install.
Before the flag
```
❯ ruby ext/semian/extconf.rb
checking for openssl/sha.h... no
openssl is missing. please install openssl.
*** ext/semian/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
--with-opt-dir
--without-opt-dir
--with-opt-include
--without-opt-include=${opt-dir}/include
--with-opt-lib
--without-opt-lib=${opt-dir}/lib
--with-make-prog
--without-make-prog
--srcdir=ext/semian
--curdir
--ruby=/nix/store/3ay21xsh45kjqfpsan7xmnf3mbng29d7-ruby-3.0.2/bin/$(RUBY_BASE_NAME)
```
After the flag
```
❯ ruby …
```
=> Allow passing --with-openssl-dir for a custom OpenSSL installation

ext/semian/resource.c
If the mark function is a noop, we might as well
just not pass it.
=> Get rid of useless mark function

lib/semian/rails.rb
When upgrading to Rails 7.1, I observed that the client_connection was `nil` sometimes. It was found out that this is caused by `@raw_connection` being used instead of `valid_raw_connection`. We are using `respond_to?` without a second parameter but the method `valid_raw_connection` is private.
```ruby
pry(#<ActiveRecord::ConnectionAdapters::VitessMysql2Adapter>)> self.class
=> ActiveRecord::ConnectionAdapters::VitessMysql2Adapter
pry(#<ActiveRecord::ConnectionAdapters::VitessMysql2Adapter>)> ::Rails.version
=> "7.1.2"
pry(#<ActiveRecord::ConnectionAdapters::VitessMysql2Adapter>)> respond_to?(:valid_raw_connection)
=> false
pry(#<ActiveRecord::ConnectionAdapters::VitessMysql2Adapter>)> respond_to?(:valid_raw_connection, true)
=> true
```
=> Fix valid_raw_connection check

.rubocop.yml, Gemfile, Gemfile.lock, lib/semian/activerecord_trilogy_adapter.rb, test/adapters/activerecord_trilogy_adapter_test.rb, test/allow_list_bench.rb
Savepoints that don't follow the activerecord pattern `active_record_savepoint_#{nesting_level}` or that are nested more than two levels are not going to bypass the circuit anymore.
I think this is okay because in the end this is a  best effort scenario on an overloaded database and this IS an active record adapter. 
In the trilogy adapter. 
We look at every single query to see wether or not it should be allowed to  pass thru the circuit if it happens to be a transaction control statement, (COMMIT/ROLLBACK/RELEASE SAVEPOINT) because we want to try our hardest to make sure we don't pile open transactions onto MySQL even if the underlying database is overloaded.
Large queries, including queries with long comments (often the case when using marginalia to pass metadata around) will in …
=> Return early from allow list when possible

.rubocop.yml, CHANGELOG.md, lib/semian/activerecord_trilogy_adapter.rb, test/adapters/activerecord_trilogy_adapter_test.rb
The `connection` method was removed in https://github.com/rails/rails/commit/6f3b46b02d190b18747a27772b0511dab71c8315
=> Fix: Trilogy ActiveRecord adapter to be compatible with latest Rails edge.

ext/semian/resource.c, ext/semian/semian.c, ext/semian/sysv_semaphores.h, lib/semian.rb, test/resource_test.rb
I just spent some time troubleshooting an issue where systemd was deleting my semaphores as a result of logind.conf having RemoveIPC=yes by default.
This will:
1. Make the error slightly easier to diagnose when it shows up in logs;
2. Provide an easier handle for an application to detect and heal.
=> Richer error handling when a semaphore array has been deleted:

CHANGELOG.md, lib/semian/mysql2.rb
- https://github.com/Shopify/resiliency/issues/3354
- https://github.com/sysown/proxysql/blob/v2.x/include/proxysql_structs.h#L455 is not currently picked up as a semian-able error
- [relevant exception in bugsnag](https://app.bugsnag.com/shopify/shopify-production/errors/654110aef7394c0008c66977?filters[event.since]=all&event_id=661939e500e6e05dab5c0000)
- update the regex array for connection errors to catch E9001
=> trigger semians when mysql connections are exhausted

README.md
A couple of minor mistakes I found in the docs when working through an implementation of dynamic sub resources.
1. `ActiveSupport::CurrentAttributes` is the correct class [docs](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html) [[code](https://github.com/Shopify/semian/pull/547/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L273)]
2. `sub_resourece_name` was assigned but then `name` was shoveled incorrectly [[code](https://github.com/Shopify/semian/pull/547/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L280)]
3. Using `attribute :name` will result in infinite recursion, presumably due to it trying to override the `.name` class method [[code](https://github.com/Shopify/semian/pull/547/files#diff-b335630551682c1 …
=> Minor fixes to example docs

Gemfile.lock, lib/semian/protected_resource.rb, lib/semian/resource.rb, test/adapters/net_http_test.rb, test/test_helper.rb
Ruby warnings often point to mistakes so it's a good idea to enable them in the test suite.
=> Avoid method redefinition warnings

ext/semian/resource.c, ext/semian/resource.h, ext/semian/semian.c, lib/semian/resource.rb, test/resource_test.rb
We're working on using Semian in a project that uses Ruby fibers and we wanted to implement MySQL bulkheads in a way where we would share the same semian resource semaphore (ticket) between multiple fibers. To be able to do that, we need to be able to acquire a semaphore without passing a block into the call and then release the semaphore later at the time of our choosing.
This PR extracts the semaphore acquisition and release logic into separate methods making the described scenario possible.
=> Explicit support for acquire_semaphore/release_semaphore in semian resources

CHANGELOG.md, lib/semian.rb, test/semian_test.rb
The default Semian's bulkhead implementation being not fiber safe makes it hard to experiment with concurrency in a larger app which relies on that implementation.
I'd like to introduce `Semian.disable_bulkheads_for_thread` which will let me experiment with async IO in an app that's using Semian's non-fiber-safe bulkheads.
Example:
```ruby
Semian.disable_bulkheads_for_thread(Thread.current) do
Async do
end
end
```
Without something like this, the 2nd fiber that tries to hit Activerecord fails with:
```
ActiveRecord::ConnectionAdapters::TrilogyAdapter::ResourceBusyError: [mysql_shard_0] timed out waiting for resource '1000mysql_shard_0'
```
=> Allow to disable bulkheads in a given thread

.devcontainer/docker-compose.yml, .github/workflows/test.yml, README.md, dockerfiles/semian-ci, examples/activerecord_trilogy_adapter/00_circuit_minimal.rb, examples/activerecord_trilogy_adapter/03_circuit_open.rb, scripts/run_tests.sh, test/adapters/activerecord_trilogy_adapter_test.rb, test/adapters/mysql2_test.rb, test/adapters/rails_tests.rb, test/config/hosts.yml
Testing locally just doesn't work for two reasons:
docker compose does not have a pinned mysql version, and so when we tried to run it, it started pulling v9, which doesn't like mysql native password plugin.
So, we decided to fix forward and just fix our tests to run on v9, which requires a password by default. This meant a few changes:
1. Start using a password and SSL (but we set the mode to 3, meaning "no verify", to simplify our setup)
2. Stop using netcat to test if mysql is up, and use mysql-client instead
The way HTTP tests work is by spinning a MockServer that is running from within the same semian container (convoluted, I know), but there is an expectation of the hostname to be `semian`, which just isn't the case when we're running tests. So I fix the hostname and also make it …
=> Fix docker compose tests

lib/semian/configuration_validator.rb
We're currently checking bulkhead configurations on environments that do not support bulkheads.
This is having the adverse effect of the validations going off in development environments, because we intentionally set MAX_TICKETS to 0 in these environments
=> Only check bulkhead configuration if semaphores are enabled

lib/semian/adapter.rb, lib/semian/circuit_breaker.rb
- Removed semian resource name from ResourceBusyError and OpenCircuitError messages since it was redundant. Both of these errors are an instance of SemianError, and this object takes semian identifier and message and modifies the message to contain semian resource name.
=> Remove redundant semian naming from error messages

Gemfile, Gemfile.lock, gemfiles/activerecord_trilogy_adapter.gemfile, gemfiles/grpc.gemfile, gemfiles/mysql2.gemfile, gemfiles/net_http.gemfile, gemfiles/rails.gemfile, gemfiles/rails_mysql2.gemfile, gemfiles/rails_trilogy.gemfile, gemfiles/redis_4.gemfile, gemfiles/redis_5.gemfile, gemfiles/redis_client.gemfile, lib/semian.rb, lib/semian/instrumentable.rb, lib/semian/simple_integer.rb, lib/semian/simple_sliding_window.rb, test/adapter_test.rb, test/semian_test.rb, test/simple_integer_test.rb, test/simple_sliding_window_test.rb, test/thread_safe_integer_test.rb, test/thread_safe_sliding_window_test.rb
Fixes #566 
Replace instances of data structures that are not thread safe and migrates existing thread safe code to use the concurrent-ruby gem
Includes unit tests to ensure correctness, thread safety and triggering race conditions will be followed up in #756
=> Make variables thread safe and introduce concurrent-ruby gem
